name: Pull Request

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-go@v5
      with:
        go-version: ^1.20
    - run: go mod download
    - name: build
      run: make build
    - name: lint
      run: make lint
    - name: test
      run: make check
    - uses: actions/upload-artifact@v3
      with:
        name: contour-authserver
        path: bin/contour-authserver # or path/to/artifact
    - uses: ncipollo/release-action@v1
      with:
        artifacts: "bin/contour-authserver"
        bodyFile: ""
    